# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 14:43
from __future__ import unicode_literals

import uuid

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """A initial migration for the model"""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
